---
- hosts: all
  become: yes
  tasks:
  - name: install apache server
    package:
      name: "{{ pack_name }}"
      state: present
    notify:
    - restart apache2
  - name: install php packages
    package:
      name: "{{ item }}"
      state: present
    with_items: "{{ php_packages }}"
    notify:
    - restart apache
  - name: download web page
    get_url:
      url: https://raw.githubusercontent.com/itsmedineshk/MyAnsible/master/basics/info.php
      dest: /var/www/html/info.php
    notify:
    - restart apache
    - restart httpd
  handlers:
  - name: restart apache
    service:
      name: "{{ pack_name }}"
      state: restarted
