# ansible -m ping all
# play
---
- hosts: all # all the inventories in your file
  become: yes
  tasks: 
  - name: execute ansible ping on hosts
    ping: 
  - name: update packages on ubuntu
    apt:
      name: git
      update_cache: yes