---
# tasks file for default
- name: install utils 
  include_tasks:
- name: install apache server
  package:
    name: "{{ pack_name }}"
    state: present
  notify:
  - restart apache2
- name: install php packages
  package:
    name: "{{ item }}"
    state: present
  with_items: "{{ php_packages }}"
  notify:
  - restart apache